language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1

notifications:
  email: false

after_success:
  # push coverage results to Coveralls and Codecov
  - julia -e 'cd(Pkg.dir("SDPA")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
